### DISCUSSION TITLE
使用cosid-example-jdbc的示例代码，但是get到的IdGenerator为null

### DISCUSSION THREAD

**Discussion by buppter** [Ahoo-Wang/CosId#232] [Q&A] [answered]
![image](https://user-images.githubusercontent.com/43202996/207858579-0ea9ad65-93be-45cd-81ff-052082fc12e7.png)
这里 `provider.getShare()`显示为null，是我使用方式不对吗，实在解决不了，还麻烦解答一下，感谢

使用的是
```xml
    <dependency>
      <groupId>me.ahoo.cosid</groupId>
      <artifactId>cosid-spring-boot-starter</artifactId>
      <version>1.16.5</version>
    </dependency>
```

**Comment by Ahoo-Wang** [comment, marked as answer]
能提供一下DEMO地址吗

**Reply by buppter** [reply]
可能不太方便，我贴代码上来吧。

使用的是springboot 2.6.14版本，pom里引入了cosid-starter后，直接使用了example里的配置。

**已经创建了cosid和cosid_machine表，但里面数据为空**

```yaml
spring:
  application:
    name: test-cosid

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: mysql-url
cosid:
  enabled: true
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: jdbc
    guarder:
      enabled: true
  snowflake:
    enabled: true
    provider:
      short_id:
        converter:
          prefix: cosid_
          type: radix
          radix:
            char-size: 11
            pad-start: false
      order_item:
        sequence-bit: 12
      snowflake:
        sequence-bit: 12
      safeJs:
        sequence-bit: 9
  segment:
    enabled: true
    mode: chain
    distributor:
      type: jdbc

    share:
      offset: 0
      step: 100
      converter:
        prefix: cosid_
        type: radix
        radix:
          char-size: 6
          pad-start: false
    provider:
      order:
        offset: 10000
        step: 100
      longId:
        offset: 10000
        step: 100

    chain:
      safe-distance: 5
      prefetch-worker:
        core-pool-size: 2
        prefetch-period: 15
```

之后定义了controller

```java
mport me.ahoo.cosid.provider.DefaultIdGeneratorProvider;
import me.ahoo.cosid.provider.IdGeneratorProvider;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;


@RestController
public class IdController {

    private final IdGeneratorProvider provider;

    public IdController() {
        this.provider = DefaultIdGeneratorProvider.INSTANCE;
    }


    @GetMapping("/id")
    public Long generateId() {
        return provider.getShare().generate();
    }
}
```

调用接口的时候会NPE
