### ISSUE TITLE
@CosId标记的是触发号段模式吗？

### ISSUE THREAD

**Issue by qinkangdeid** [Ahoo-Wang/CosId#113]
debug的时候配置的是:
```yaml
cosid:

  namespace: ${spring.application.name}
  snowflake:
    enabled: true
    machine:
      distributor:
        type: redis


```
默认是share的ID生成器吧   我代码获取的和 @Cosid生成的数字不一直  刚刚开始看代码 有点懵逼 望解答
代码是这样获取的
```java
      // 获取的是 315557917682049024    3开头的
      long id = idGeneratorProvider.getShare().generate();
``` 

 实体打注解的   
  ```java 
     // 生成的id为 ：6922446069401911327
    @CosId
    @TableId(value = "id", type = IdType.INPUT)
    private Long id;


```
