### ISSUE TITLE
Invalid file path

### ISSUE THREAD

**Issue by AntarcticBruin** [Ahoo-Wang/CosId#143]
Error creating bean with name 'shareSnowflakeId' defined in class path resource [me/ahoo/cosid/spring/boot/starter/snowflake/CosIdSnowflakeAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [me.ahoo.cosid.snowflake.SnowflakeId]: Factory method 'shareSnowflakeId' threw exception; nested exception is me.ahoo.cosid.CosIdException: java.io.IOException: Invalid file path

**Comment by Ahoo-Wang** [comment]
We were unable to reproduce the issue (https://github.com/Ahoo-Wang/CosId/actions/runs/2869266395).
Can you provide more information about this Issue, as described by issue_template(https://github.com/Ahoo-Wang/CosId/blob/main/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by clinmanc** [comment]
`state-storage: enabled: false` removed since 1.14.6,  But I don't want to use state storage. How can I configure. since 1.4.6, it throws this error

```yaml
cosid:
  machine:
    enabled: true
    stable: true
    state-storage:
      enabled: false // removed since 1.14.6
    distributor:
      type: manual
      manual:
        machine-id: 0
    guarder:
      enabled: false
    clock-backwards:
      spin-threshold: 1
      broken-threshold: 10000
  snowflake:
    enabled: true
    epoch: 1659283200000
    share:
      clock-sync: true
      friendly: true
```
