### ISSUE TITLE
mybatis id

### ISSUE THREAD

**Issue by boot-vue** [Ahoo-Wang/CosId#24]
`1.7.9`

```yaml
cosid:
  namespace: ${spring.application.name}
  segment:
    enabled: true
    mode: chain
    chain:
      safe-distance: 5
      prefetch-worker:
        core-pool-size: 2
        prefetch-period: 1s
    distributor:
      type: redis
    share:
      offset: 5
      step: 100
      converter:
        prefix:
        type: radix
        radix:
          char-size: 6
          pad-start: false
    provider:
      order:
        offset: 1
        step: 100
```

```java
@Cosid(value="order")
private Long id;
```

`id`指定了`provider`是`order`,  mybatis实际插入数据库为何每次都是按照`share`的`offset`开始插入,  是用的姿势不对吗?

```java
     new User(null, "张三");
   
    @Insert(value = "insert into user values (#{id} ,#{name} )")
    void save(User xx);
```
