### ISSUE TITLE
radix  generateAsString() 如何生成纯数字字符串

### ISSUE THREAD

**Issue by boot-vue** [Ahoo-Wang/CosId#285]
```yml

cosid:
  segment:
    ......
    share:
      offset: 0
      step: 10
      converter:
        type: radix
        radix:
          pad-start: true
          char-size: 8
```

`idGeneratorProvider.getShare().generateAsString()`  看代码实现 内部用的`char[]`来填充字符

最终生成的字符串类似这样    `000000Fd`  内容不符合预期

`cosid`有没有能直接生成   `00000001`   这样纯数字字符串的方式    不想额外处理了
