### ISSUE TITLE
Cosid JdbcIdSegmentDistributor 支持多数据库么?

### ISSUE THREAD

**Issue by googlefan** [Ahoo-Wang/CosId#558]
文档中介绍JdbcIdSegmentDistributor 支持各种关系型数据库。看代码 mysql 支持的是没问题的,但是oracle 的环境下执行报错:
function unix_timestamp not exits . 
    public static final String INCREMENT_MAX_ID_SQL
        = "update cosid set last_max_id=(last_max_id + ?),last_fetch_time=unix_timestamp() where name = ?;";
应该是不支持 oracle 系列的数据库吧?

**Comment by Ahoo-Wang** [comment]
@googlefan 
1. `cosid-jdbc` 依赖 Java JDBC 接口，并不直接依赖具体数据库，即 `cosid-jdbc` 支持所有实现了 Java JDBC 规范的数据库。
2. 不同的数据库具有不同 SQL 方言/语法，目前 `cosid-jdbc` 并没有内置所有 SQL 方言(如你所见，默认内置了 MySql 方言)，即你所看到的如下
https://github.com/Ahoo-Wang/CosId/blob/f537b43cde3f2ed974e8f93945300f4362eb67ec/cosid-jdbc/src/main/java/me/ahoo/cosid/jdbc/JdbcIdSegmentDistributor.java#L40
3. 但这只是默认值，正如`JdbcIdSegmentDistributor`构造函数所示
https://github.com/Ahoo-Wang/CosId/blob/f537b43cde3f2ed974e8f93945300f4362eb67ec/cosid-jdbc/src/main/java/me/ahoo/cosid/jdbc/JdbcIdSegmentDistributor.java#L56
4. 用户可以自己定义 `incrementMaxIdSql` / `fetchMaxIdSql` 参数，以支持不同数据库的方言
5. 该配置可以通过如下配置自定义
```yaml
  segment:
    distributor:
      type: jdbc
      jdbc:
        increment-max-id-sql:
        fetch-max-id-sql:
```
