### ISSUE TITLE
引入CosId作为业务单据编号的发号器遇到一些问题

### ISSUE THREAD

**Issue by HenryGyu** [Ahoo-Wang/CosId#743]
我尝试使用CosId作为业务单据编号的发号器，采用的是号段模式，并有配置日期前缀，具体配置如下：
```yaml
cosid:
  # namespace: ${APP_NAME}
  segment:
    enabled: true
    distributor:
      type: jdbc
    share:
      enabled: false
    provider:
      date_prefix_no:
        offset: 0
        converter:
          type: to_string
          prefix: BIZ
          date-prefix:
            enabled: true
            pattern: yyMMdd
            delimiter:
          to-string:
            char-size: 3
            pad-start: true
```

目前的号段模式下，last_max_id不会在第二天进行重置，而实际业务希望的是，第一天取号如下：
BIZ250318001、BIZ250318002、BIZ250318003 ...

第二天编号会重置如下：
BIZ250319001、BIZ250319002、BIZ250319003 ...

所以CosId是否可以考虑在年月日前缀变化时，号段会重置呢。

另外`to-string`配置和`date-prefix`配置不能组合使用，这里的`to-string`配置不生效
