### ISSUE TITLE
序号重置为0的触发条件是怎样的

### ISSUE THREAD

**Issue by HenryGyu** [Ahoo-Wang/CosId#748]
作者好，昨天有提到过序号重置为0的问题，感谢您的答复，但我今天在测试的时候发现重置为0并没有生效，我的测试过程如下：

```
cosid:
  segment:
    enabled: true
    distributor:
      type: jdbc
    share:
      enabled: false
    provider:
      test:
        offset: 0
        group:
          by: year_month_day
          pattern: yyMMdd
        converter:
          type: to_string
          to-string:
            char-size: 3
            pad-start: true
          prefix: BIZ
          group-prefix:
            enabled: true
            delimiter:
```

上面的配置是按年月日重置，测试几轮取号没问题后，我将数据库的 `last_fetch_time` 手动修改为昨天的日期，然后重启项目，再次取号发现序号并没有重置。

![Image](https://github.com/user-attachments/assets/50217a0e-888d-4049-a53e-bda0350b9a4b)

![Image](https://github.com/user-attachments/assets/53c4da79-6900-4eb1-8bc7-b6ee2661dd2d)
