### ISSUE TITLE
希望CosIdProxyServer支持高可用场景部署

### ISSUE THREAD

**Issue by tqsummer** [Ahoo-Wang/CosId#784]
**Is your feature request related to a problem? Please describe.**
1.​客户端单点依赖：客户端启动时仅注册到第一台Proxy-Server，未自动感知第二台节点，导致负载不均和单点风险。
​2.状态/数据不一致：第二台Proxy-Server无法正确处理客户端请求（如Guard校验失败、号段分配异常），表明节点间状态或数据未同步。
​3.缺乏故障自动切换：客户端未实现动态重试或节点切换逻辑，依赖人工干预恢复服务。（希望能支持注册服务发现调用）

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ahoo-Wang** [comment]
[v2.12.5](https://github.com/Ahoo-Wang/CosId/releases/tag/v2.12.5) 使用 [CoApi](https://github.com/Ahoo-Wang/CoApi) 替代 OkHttp ，集成 spring cloud 客户端负载均衡。

下面是 simple 使用案例：

```yaml
server:
  port: 8600
spring:
  application:
    name: ${service.name:cosid-example-proxy}

  cloud:
    discovery:
      client:
        simple:
          instances:
            cosid-proxy:
              - host: localhost
                port: 8688
              - host: localhost
                port: 8788
cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: proxy
    guarder:
      enabled: true
  snowflake:
    enabled: true
  proxy:
    host: lb://cosid-proxy # 当前缀使用 lb ，即为客户端负载均衡

logging:
  level:
    me.ahoo.cosid: debug

```
