### ISSUE TITLE
spring-cloud-commons 包的引入导致的  CompatibilityNotMetException

### ISSUE THREAD

**Issue by luoren18** [Ahoo-Wang/CosId#8]
cosid-spring-boot-starter   由于  spring-cloud-commons 包的引入会抛出 兼容性的异常 `CompatibilityNotMetException`，可以根据提示在配置文件中配置
```yaml
spring:
  cloud:
    compatibility-verifier:
      enabled: false
```
可以解决。
