### ISSUE TITLE
这个支持生成的 ID 能自定义么

### ISSUE THREAD

**Issue by banduoba** [Ahoo-Wang/CosId#9]
比如生成10位,不需要过长的,
另外是否可以指定以固定数字开头或者固定字母开头使 ID 容易分辨

**Comment by Ahoo-Wang** [comment]
> 比如生成10位,不需要过长的

你是指 CosId 提供的 `SnowflakeId ` , 还是 `SegmentId ` ？

如果是  `SnowflakeId `，你可以自定义位分配方案。
https://github.com/Ahoo-Wang/CosId/blob/main/wiki/getting-started.md#idgeneratorprovider

> 另外是否可以指定以固定数字开头或者固定字母开头使 ID 容易分辨

https://github.com/Ahoo-Wang/CosId/blob/main/cosid-core/src/main/java/me/ahoo/cosid/IdGenerator.java

你可以包装一下 `IdGenerator` 来达到你的需求。

**Comment by Ahoo-Wang** [comment]
*v1.5.0*

https://github.com/Ahoo-Wang/CosId/commit/90d1a624f26338f7411434858f8396dd7cb4d2d0

```yaml
    provider:
      short_id:
        converter:
          prefix: cosid_
          type: radix
          radix:
            char-size: 10
            pad-start: false
```

`cosid_JWu5ySiHJ2`
